### PR TITLE
target of repo

### LINKED ISSUE #4: Renew this repo
Hi @fastify/fastify 
since this repo is not still used, could we organize it with a wide range of examples in a "monorepo" way?

It could be related to the [blog post](https://github.com/orgs/fastify/teams/fastify/discussions/51?from_comment=10#discussion-51-comment-10) in order to link a complete and working example, meanwhile, the blog has only some piece of code and nice slides 😜

Opening this issue after this review
Ref https://github.com/fastify/fastify/pull/1588/files#r277096324

### PR DESCRIPTION
**Pull request by Eomm**
Closes #4 

What you would change/add?

PS 😇:
`remote: Permission to fastify/example.git denied to Eomm.`

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by delvedor** [comment]
I've added this repo to the core team :)

**Comment by Eomm** [comment]
@delvedor I don't have write access to this repo: could I in order to start building some examples?

**Comment by mcollina** [comment]
done

**Comment by Eomm** [comment]
😇

image

image

**Pull request merged**
