### PR TITLE
WIP: Adding good tests example

### PR DESCRIPTION
**Pull request by veritem**
regarding https://github.com/fastify/fastify/issues/1367

### CODE REVIEW

**Comment by mcollina** [comment]
good work so far!

**Comment by jsumners** [comment]
I have converted this to a draft PR. Please remove the "WIP" and click the "Ready for review" button when complete.

**Review by mcollina — CHANGES_REQUESTED** [review]
Could you add 'use strict' everywhere? Also, could you set up github actions so that it runs the tests? I might be wrong, but I think this needs linting.

**Comment by rubiagatra** [comment]
Is there any update for this draft @veritem ?

**Comment by veritem** [comment]
school took the whole of me, I'll get it done shortly @rubiagatra

**Comment by veritem** [comment]
not sure why you closed this @climba03003

**Comment by climba03003** [comment]
Resolved by another PR. #19

**Pull request closed without merging**
